stages:
  - scc
  - genLicense
  - checkLicense
  - build_tc32
  - build_riscv
  - cov
  - fossid
  - plainPW_check
  - oss
  - misspellChecking

scc:
  stage: scc
  script:
    - echo "Enter scc stage"
    - scc | tee scc.txt
    - bash /usr/bin/scc_calc.sh
    - echo  "The End SCC result:"
    - cat scc.txt
  artifacts:
    paths:
    - scc.txt

genLicense:
  variables:
    CODE_COMPILE_ARCH: 'EAGLE_ANDES'
    COV_PF_CATALOG: 'ZIGBEE'
  stage: genLicense
  before_script:
  script:
    - date
    - generat_license_list
    - date
  artifacts:
    paths:
    - "license_list_gen.txt"
    - "no_license_list_gen.txt"
    - "mismatch_license_file_gen.txt"
  when: manual

checkLicense:
  variables:
    CODE_COMPILE_ARCH: 'EAGLE_ANDES'
    COV_PF_CATALOG: 'ZIGBEE'
  stage: checkLicense
  allow_failure: yes
  before_script:
  script:
    - date
    - check_license
    #- generat_license_list # For no license files
    - date

  artifacts:
    when: always
    paths:
    - "mismatch_license.txt"
    - "no_license*.txt"
    - "unknow_type_file.txt"

build_tc32:
  stage: build_tc32
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x tl_zigbee_sdk/tools/*.sh
    - date
    - ls tl_zigbee_sdk/build/tlsr_tc32
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS1  -import tl_zigbee_sdk/build/tlsr_tc32 -cleanBuild tl_zigbee_sdk/sampleLight_8258
    - date

  artifacts:
    paths:
    - "tl_zigbee_sdk/build/tlsr_tc32/sampleLight_8258/*.bin"
    - "tl_zigbee_sdk/build/tlsr_tc32/sampleLight_8258/*.lst"
    - "tl_zigbee_sdk/build/tlsr_tc32/sampleLight_8258/*.elf"

build_riscv:
  variables:    
    CODE_COMPILE_ARCH: 'EAGLE_ANDES'    
    COV_PF_CATALOG: 'ZIGBEE'  
  stage: build_riscv
  before_script:
  script:
    - ls
    - pwd
    - chmod +x tl_zigbee_sdk/tools/*.sh
    - date
    - echo "--------------- Will build Demo -----------------"
    - echo #$ECLIPSE_PROJECT/$ECLIPSE_BUILD_TARGET
    - $ANDESRISCV_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import tl_zigbee_sdk/build/tlsr_riscv -cleanBuild tl_zigbee_sdk/sampleLight_9518
    - date
    - simpleMemoryMap.sh riscv32-elf-readelf | tee mm.csv
    - MemoryMap_Pretty.py mm.csv | tee mm_pretty.csv

  artifacts:
    paths:
    - "tl_zigbee_sdk/build/tlsr_riscv/sampleLight_9518/output/*.bin"
    - "tl_zigbee_sdk/build/tlsr_riscv/sampleLight_9518/*.elf"
    - mm_pretty.csv
    
# The cov job definition
cov:
  variables:    
    CODE_COMPILE_ARCH: 'TC32'    
    COV_PF_CATALOG: 'ZIGBEE'  
  stage: cov 
  tags:    
    - COV    
    - LINUX    
    - TC32
  before_script:  
  script:    
    - chmod +x tl_zigbee_sdk/tools/*.sh    
    - $COV_B COV_$CI_PROJECT_NAME $COV_B_TEMPLATE/$CODE_COMPILE_ARCH $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import tl_zigbee_sdk/build/tlsr_tc32  -cleanBuild tl_zigbee_sdk/sampleLight_8258    
    - $COV_A COV_$CI_PROJECT_NAME    
    - cov_add_commit_steam_project_2_platform.sh
  when: manual
        
fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  when: manual

plainPW_check:
  stage: plainPW_check 
  script:
    - echo "Enter Plain Password checking stage"
    - check_plain_weak_password | tee result.txt
    - ls -l result.txt
    - echo "Error List:"
    - cat result.txt
  artifacts:
    paths:
    - result.txt
  when: manual

oss:
  tags:
    - OSS
  stage: oss
  script:
    - oss_checking .
  artifacts:
    paths:
    - scan_result
  when: manual

misspellChecking:
  stage: misspellChecking
  variables:
    pattern: "./tl_zigbee_sdk/platform/chip_tl321x/lib/include/pke/pke.h
              ./tl_zigbee_sdk/platform/chip_tl321x/lib/include/pke/pke.h
              ./tl_zigbee_sdk/platform/chip_tl321x/lib/include/pke/pke.h
              ./tl_zigbee_sdk/platform/chip_tl321x/lib/include/pke/pke.h
              ./tl_zigbee_sdk/platform/chip_b91/reg_include/core_reg
              ./tl_zigbee_sdk/platform/chip_b92/reg_include/core_reg.h
              ./tl_zigbee_sdk/platform/chip_tl321x/reg_include/core_reg.h
              ./tl_zigbee_sdk/platform/chip_tl721x/reg_include/core_reg.h
              ./tl_zigbee_sdk/apps/sampleLight/sampleLightCtrl.c
              ./tl_zigbee_sdk/apps/sampleLight/sampleLightEpCfg.c
              ./tl_zigbee_sdk/apps/sampleLight/sampleLight.h
              ./tl_zigbee_sdk/apps/sampleLight/zcl_sceneCb.c
              ./tl_zigbee_sdk/apps/sampleLight/zcl_colorCtrlCb.c"
    word_filter_pattern: "monts SIE currentY"
  tags:
    - LINUX
  script:
    - echo "--------------- Begin ------------------------"
    - misspell-check
    - echo "---------------- End -----------------------"
  artifacts:
    paths:
    - misspell_result.txt
    
